
// This file has been generated by the GUI designer. Do not modify.
namespace browsertest
{
	public partial class WarningWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview3;

		private global::Gtk.Button button13;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget browsertest.WarningWindow
			this.Name = "browsertest.WarningWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("WarningWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child browsertest.WarningWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.textview3.Editable = false;
			this.GtkScrolledWindow.Add(this.textview3);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button13 = new global::Gtk.Button();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = global::Mono.Unix.Catalog.GetString("Retry");
			this.vbox2.Add(this.button13);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button13]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 368;
			this.DefaultHeight = 126;
			this.Show();
			this.button13.Clicked += new global::System.EventHandler(this.OnClick);
		}
	}
}
