
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action PersonalizeAction;

	private global::Gtk.Action EditHomepageAction;

	private global::Gtk.Action ToolsAction;

	private global::Gtk.Action BulkDownloadAction;

	private global::Gtk.Action QuitAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.PersonalizeAction = new global::Gtk.Action("PersonalizeAction", global::Mono.Unix.Catalog.GetString("Personalize"), null, null);
		this.PersonalizeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Personalize");
		w1.Add(this.PersonalizeAction, null);
		this.EditHomepageAction = new global::Gtk.Action("EditHomepageAction", global::Mono.Unix.Catalog.GetString("Edit Homepage"), null, null);
		this.EditHomepageAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit Homepage");
		w1.Add(this.EditHomepageAction, null);
		this.ToolsAction = new global::Gtk.Action("ToolsAction", global::Mono.Unix.Catalog.GetString("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tools");
		w1.Add(this.ToolsAction, null);
		this.BulkDownloadAction = new global::Gtk.Action("BulkDownloadAction", global::Mono.Unix.Catalog.GetString("Bulk Download"), null, null);
		this.BulkDownloadAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Bulk Download");
		w1.Add(this.BulkDownloadAction, null);
		this.QuitAction = new global::Gtk.Action("QuitAction", global::Mono.Unix.Catalog.GetString("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quit");
		w1.Add(this.QuitAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='PersonalizeAction' action='PersonalizeAction'><menuitem name='EditHomepageAction' action='EditHomepageAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='BulkDownloadAction' action='BulkDownloadAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseStock = true;
		this.button4.UseUnderline = true;
		this.button4.Label = "gtk-go-back";
		this.hbox1.Add(this.button4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseStock = true;
		this.button5.UseUnderline = true;
		this.button5.Label = "gtk-go-forward";
		this.hbox1.Add(this.button5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button5]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Favourites");
		this.hbox1.Add(this.button6);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button6]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry1]));
		w6.Position = 3;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("History");
		this.hbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		w7.Padding = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseStock = true;
		this.button2.UseUnderline = true;
		this.button2.Label = "gtk-refresh";
		this.hbox1.Add(this.button2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button2]));
		w8.Position = 5;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(3));
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseStock = true;
		this.button3.UseUnderline = true;
		this.button3.Label = "gtk-home";
		this.hbox1.Add(this.button3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button3]));
		w9.Position = 6;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(3));
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.Overwrite = true;
		this.GtkScrolledWindow.Add(this.textview1);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w12.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 937;
		this.DefaultHeight = 652;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.EditHomepageAction.Activated += new global::System.EventHandler(this.EditHomepage);
		this.BulkDownloadAction.Activated += new global::System.EventHandler(this.OnBulkClick);
		this.QuitAction.Activated += new global::System.EventHandler(this.OnFileQuit);
		this.button4.Clicked += new global::System.EventHandler(this.OnBackClick);
		this.button5.Clicked += new global::System.EventHandler(this.OnForwardClick);
		this.button6.Clicked += new global::System.EventHandler(this.FavClick);
		this.entry1.Activated += new global::System.EventHandler(this.OnSearchActivation);
		this.button1.Clicked += new global::System.EventHandler(this.OnHistory);
		this.button2.Clicked += new global::System.EventHandler(this.RefreshClick);
		this.button3.Clicked += new global::System.EventHandler(this.HomeClick);
	}
}
